# This is your Editor pane.
version: '2'
services:
  web: 
    image: wordpress
    ports: 
      - 8000:80
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wp
      - WORDPRESS_DB_PASSWORD=wpdb
      
  mysql:
    image: mysql:5.7
    ports: 
      - 3306:3306
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=wpdb
      - MYSQL_ROOT_PASSWORD=mysql
  
